# Based on: https://github.com/marketplace/actions/setup-miniconda#example-1-basic-usage

name: Base Juno pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: 
          - {os: macOS-latest}
          - {os: ubuntu-18.04}
          - {os: ubuntu-latest}
    name: Testing main classes ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setting up conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "0.22.1"
          channels: conda-forge, anaconda, bioconda, biocore, defaults
          channel-priority: true
          environment-file: base_juno_pipeline/envs/master_env.yaml 
          activate-environment: base_juno
          auto-activate-base: false
      - name: Conda list
        shell: bash -l {0}
        run: conda list
      - name: Test base
        shell: bash -l {0}
        run: python tests/test_base_juno_pipeline.py
